export const CREATE_USER = 'USER/CREATE_USER'
export const CHECK_USER = 'USER/CHECK_USER'

export const UPLOAD_PRODUCTS = 'PRODUCT/UPLOAD_PRODUCTS'
export const UPLOAD_SINGLE_PRODUCT = 'PRODUCT/UPLOAD_SINGLE_PRODUCT'

export const ADD_REMOVE_MANUFACTURER = 'FILTER/ADD_REMOVE_MANUFACTURER'
export const UPLOAD_MANUFACTURERS = 'FILTER/UPLOAD_MANUFACTURERS'
export const DELETE_MANUFACTURERS = 'FILTER/DELETE_MANUFACTURERS'

export const MANUFACTURERS_PRICE_ASCENDING = 'FILTER/MANUFACTURERS_PRICE_ASCENDING'
export const MANUFACTURERS_PRICE_DESCENDING = 'FILTER/MANUFACTURERS_PRICE_DESCENDING'